name: IndexNow

on:
  push:
    branches:
      - master
  schedule:
    # Set the schedule time
    - cron: '0 2 * * *'
  
jobs:
  submit: 
    runs-on: ubuntu-latest
    steps:
      - name: 提交链接
        uses: bojieyang/indexnow-action@v2
        with:
          # The location of the sitemap(e.g., https://example.com/sitemap.xml).
          sitemap-location: 'https://justpureh2o.cn/sitemap-0.xml'
          # URLs with `lastmod` fields in sitemap files within the last {since} {since-unit} will be submitted.
          key: '888c17b59562490f866e799aeac0f717'
          
